//SRC0_SEL.ALU_SRC_HW_WAVE_ID SRC0_CHAN.CHAN_X;
//SRC0_SEL.ALU_SRC_SIMD_ID SRC0_CHAN.CHAN_X;
//SRC0_SEL.ALU_SRC_SE_ID SRC0_CHAN.CHAN_X;
//SRC0_SEL.ALU_SRC_HW_THREADGRP_ID SRC0_CHAN.CHAN_X;
//SRC0_SEL.ALU_SRC_WAVE_ID_IN_GRP SRC0_CHAN.CHAN_X;
//SRC0_SEL.ALU_SRC_NUM_THREADGRP_WAVES SRC0_CHAN.CHAN_X;

ALU:
  BARRIER;

  MOV:
    SRC0_SEL.ALU_SRC_HW_THREADGRP_ID SRC0_CHAN.CHAN_X;
    WRITE_MASK DST_GPR(4) DST_CHAN.CHAN_X;

  MOV:
    SRC0_SEL.ALU_SRC_0;
    WRITE_MASK DST_GPR(4) DST_CHAN.CHAN_Y;

  MOV:
    SRC0_SEL.ALU_SRC_0;
    WRITE_MASK DST_GPR(4) DST_CHAN.CHAN_Z;

  MOV:
    SRC0_SEL.ALU_SRC_0;
    WRITE_MASK DST_GPR(4) DST_CHAN.CHAN_W;
    LAST;

ALU:
  BARRIER;

  MOV:
    SRC0_SEL.ALU_SRC_LITERAL SRC0_CHAN.CHAN_X;
    DST_GPR(2) DST_CHAN.CHAN_X;
    LAST;
    0x00000100;
    0x00000000;

  MULLO_INT:
    SRC0_SEL.ALU_SRC_PV SRC0_CHAN.CHAN_X;
    SRC1_SEL.GPR(1) SRC1_CHAN.CHAN_X;
    DST_GPR(2) DST_CHAN.CHAN_X;

  MULLO_INT:
    SRC0_SEL.ALU_SRC_PV SRC0_CHAN.CHAN_X;
    SRC1_SEL.GPR(1) SRC1_CHAN.CHAN_Y;
    DST_GPR(2) DST_CHAN.CHAN_Y;

  MULLO_INT:
    SRC0_SEL.ALU_SRC_PV SRC0_CHAN.CHAN_X;
    SRC1_SEL.GPR(1) SRC1_CHAN.CHAN_Z;
    DST_GPR(2) DST_CHAN.CHAN_Z;

  MULLO_INT:
    SRC0_SEL.ALU_SRC_PV SRC0_CHAN.CHAN_X;
    SRC1_SEL.GPR(1) SRC1_CHAN.CHAN_W;
    DST_GPR(2) DST_CHAN.CHAN_W;
    LAST;

  ADD_INT:
    SRC0_SEL.ALU_SRC_PV SRC0_CHAN.CHAN_X;
    SRC1_SEL.GPR(0) SRC1_CHAN.CHAN_X;
    WRITE_MASK DST_GPR(2) DST_CHAN.CHAN_X;

  ADD_INT:
    SRC0_SEL.ALU_SRC_PV SRC0_CHAN.CHAN_Y;
    SRC1_SEL.GPR(0) SRC1_CHAN.CHAN_Y;
    WRITE_MASK DST_GPR(2) DST_CHAN.CHAN_Y;

  ADD_INT:
    SRC0_SEL.ALU_SRC_PV SRC0_CHAN.CHAN_Z;
    SRC1_SEL.GPR(0) SRC1_CHAN.CHAN_Z;
    WRITE_MASK DST_GPR(2) DST_CHAN.CHAN_Z;

  ADD_INT:
    SRC0_SEL.ALU_SRC_PV SRC0_CHAN.CHAN_W;
    SRC1_SEL.GPR(0) SRC1_CHAN.CHAN_W;
    WRITE_MASK DST_GPR(2) DST_CHAN.CHAN_W;
    LAST;

NOP:
  BARRIER;

MEM_RAT_CACHELESS:
  RAT_ID(11) RAT_INST.EXPORT_RAT_INST_STORE_RAW TYPE(1) RW_GPR(2) INDEX_GPR(2) ELEM_SIZE(3);
  COMP_MASK(1) BARRIER ARRAY_SIZE(0);

NOP: 
  BARRIER END_OF_PROGRAM;

end;
