ALU:
  BARRIER;
  
  MULLO_INT:
    SRC0_SEL.GPR(0) SRC0_CHAN.CHAN_X ///< local_ID.x
    SRC1_SEL.ALU_SRC_LITERAL SRC1_CHAN.CHAN_X 
    WRITE_MASK DST_GPR(0) DST_CHAN.CHAN_X;
    LAST;
    0x4;
    0x0;
    
  MULLO_INT:
    SRC0_SEL.GPR(1) SRC0_CHAN.CHAN_X ///< group_ID.x
    SRC1_SEL.ALU_SRC_LITERAL SRC1_CHAN.CHAN_X 
    WRITE_MASK DST_GPR(1) DST_CHAN.CHAN_X;
    LAST;
    0x400;
    0x0;

  ADD_INT:
    SRC0_SEL.GPR(0) SRC0_CHAN.CHAN_X
    SRC1_SEL.GPR(1) SRC1_CHAN.CHAN_X 
    WRITE_MASK DST_GPR(0) DST_CHAN.CHAN_X;
    LAST;
  
MEM_RAT_CACHELESS:
  RAT_ID(11) RAT_INST.EXPORT_RAT_INST_STORE_RAW TYPE(1) RW_GPR(0) INDEX_GPR(0) ELEM_SIZE(0);
  COMP_MASK(15) BARRIER ARRAY_SIZE(0);

NOP: 
  BARRIER END_OF_PROGRAM;

end;
