//SRC0_SEL.ALU_SRC_HW_WAVE_ID SRC0_CHAN.CHAN_X;
//SRC0_SEL.ALU_SRC_SIMD_ID SRC0_CHAN.CHAN_X;
//SRC0_SEL.ALU_SRC_SE_ID SRC0_CHAN.CHAN_X;
//SRC0_SEL.ALU_SRC_HW_THREADGRP_ID SRC0_CHAN.CHAN_X;
//SRC0_SEL.ALU_SRC_WAVE_ID_IN_GRP SRC0_CHAN.CHAN_X;
//SRC0_SEL.ALU_SRC_NUM_THREADGRP_WAVES SRC0_CHAN.CHAN_X;

ALU:
  BARRIER;

  MOV:
    SRC0_SEL.ALU_SRC_HW_WAVE_ID SRC0_CHAN.CHAN_X
    WRITE_MASK DST_GPR(4) DST_CHAN.CHAN_X;
    LAST;

ALU:
  BARRIER;

  MULLO_INT:
    SRC0_SEL.GPR(1) SRC0_CHAN.CHAN_X ///< group_ID.x
    SRC1_SEL.ALU_SRC_LITERAL SRC1_CHAN.CHAN_X 
    WRITE_MASK DST_GPR(2) DST_CHAN.CHAN_X;
    LAST;
    0x00000100;
    0x00000000;

  ADD_INT:
    SRC0_SEL.GPR(0) SRC0_CHAN.CHAN_X ///< local_ID.x
    SRC1_SEL.GPR(2) SRC1_CHAN.CHAN_X 
    WRITE_MASK DST_GPR(3) DST_CHAN.CHAN_X;
    LAST;

NOP:
  BARRIER;

MEM_RAT_CACHELESS:
  RAT_ID(11) RAT_INST.EXPORT_RAT_INST_STORE_RAW TYPE(1) RW_GPR(4) INDEX_GPR(3) ELEM_SIZE(0);
  COMP_MASK(1) BARRIER ARRAY_SIZE(0);

NOP: 
  BARRIER END_OF_PROGRAM;

end;
